const columnsTemplateDistributionAnalyse = [
  { header: "", key: "1", width: 32 },
  { header: "", key: "2", width: 3 },
  { header: "", key: "3", width: 32 },
  { header: "", key: "4", width: 3 },
  { header: "", key: "5", width: 32 },
  { header: "", key: "6", width: 3 },
  { header: "", key: "7", width: 32 },
  { header: "", key: "8", width: 17 },
  { header: "", key: "9", width: 17 },
  { header: "", key: "10", width: 17 },
  { header: "", key: "11", width: 17 },
  { header: "", key: "12", width: 17 },
  { header: "", key: "13", width: 17 },
  { header: "", key: "14", width: 17 },
  { header: "", key: "15", width: 17 },
  { header: "", key: "16", width: 17 },
  { header: "", key: "17", width: 17 },
  { header: "", key: "19", width: 17 },
  { header: "", key: "20", width: 17 },
];
export default columnsTemplateDistributionAnalyse;
